#!/usr/bin/env python3
"""
Provenance map -- which function produces which manuscript number
=============================================================================
Type:           PAPER (audit; reads source text, runs no simulation)
Paper Sec.:     n/a (repository traceability)
Experiment:     manuscript data-provenance mapping
What it does:   Every quantitative claim in the manuscript is registered exactly
                once, as a ``claim(...)`` / ``claim_order(...)`` call inside
                verify_numerics.py.  The fifth positional argument of each call
                IS the expression that produces the number.  This script parses
                that file with ``ast`` and renders, per paper section:

                    manuscript quantity | where it appears | produced by

                together with a symbol table resolving the short names used in
                those expressions (``br``, ``p50``, ``dmg``, ...) to the module,
                function or JSON artefact they stand for.

                This is deliberately GENERATED rather than hand-maintained: a
                hand-written provenance table goes stale the first time someone
                renames a function, which is exactly the failure mode it exists
                to prevent.  Add a claim to verify_numerics.py and this map
                picks it up on the next run.

Outputs:        the block between the BEGIN/END PROVENANCE markers in README.md.
                There is deliberately no second copy of the table elsewhere: an
                earlier draft of this script also wrote provenance_report.md,
                which duplicated the README block verbatim.
Dependencies:   reads scripts/verify_numerics.py and README.md; no simulation.
=============================================================================
"""
from __future__ import annotations

import ast
import io
import os
import sys

os.environ.setdefault("PYTHONUNBUFFERED", "1")
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(line_buffering=True)
    sys.stderr.reconfigure(line_buffering=True)

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
VERIFY = os.path.join(HERE, "verify_numerics.py")
README = os.path.join(ROOT, "README.md")

BEGIN = "<!-- BEGIN PROVENANCE (generated by scripts/provenance_map.py) -->"
END = "<!-- END PROVENANCE -->"

CLAIM_FUNCS = ("claim", "claim_order")


def _call_name(node):
    if isinstance(node, ast.Call):
        f = node.func
        if isinstance(f, ast.Name):
            return f.id
        if isinstance(f, ast.Attribute):
            return f.attr
    return None


def _lit(node, default="?"):
    try:
        return ast.literal_eval(node)
    except Exception:
        try:
            return ast.unparse(node)
        except Exception:
            return default


def collect_symbols(tree):
    """Explain every short name that actually appears in a producing expression.

    The set is derived FROM the claim expressions rather than hard-coded, so a
    new intermediate variable (``sig_ov_m``, ``M_PSI``, ...) explains itself the
    first time it is used and the table can never be missing a symbol.
    """
    used = set()
    for node in ast.walk(tree):
        if _call_name(node) in CLAIM_FUNCS and len(node.args) > 4:
            for sub in ast.walk(node.args[4]):
                if isinstance(sub, ast.Name):
                    used.add(sub.id)

    defs = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for a in node.names:
                if a.asname:
                    defs[a.asname] = "`%s` module" % a.name
        elif (isinstance(node, ast.Assign) and len(node.targets) == 1
              and isinstance(node.targets[0], ast.Name)):
            name = node.targets[0].id
            v = node.value
            if (isinstance(v, ast.Call) and _call_name(v) == "load_json"
                    and v.args):
                defs[name] = "`%s`" % _lit(v.args[0])
            else:
                try:
                    defs[name] = "`%s`" % ast.unparse(v)
                except Exception:
                    pass

    return {k: defs[k] for k in used if k in defs}


def collect_claims(tree):
    """Walk the file in source order, tracking the running ``S = "<section>"``."""
    loops = []
    for n in ast.walk(tree):
        if isinstance(n, ast.For):
            end = max((getattr(x, "lineno", n.lineno) for x in ast.walk(n)),
                      default=n.lineno)
            loops.append((n.lineno, end))

    events = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and t.id == "S":
                    try:
                        val = ast.literal_eval(node.value)
                    except Exception:
                        val = None
                    if isinstance(val, str):
                        events.append((node.lineno, 0, val))
        if _call_name(node) in CLAIM_FUNCS:
            events.append((node.lineno, 1, node))
    events.sort(key=lambda e: (e[0], e[1]))

    rows = []
    section = "(unlabelled)"
    for _, kind, payload in events:
        if kind == 0:
            section = payload
            continue
        args = payload.args
        quantity = _lit(args[1]) if len(args) > 1 else "?"
        where = _lit(args[2]) if len(args) > 2 else "?"
        try:
            source = ast.unparse(args[4]) if len(args) > 4 else "?"
        except Exception:
            source = "?"
        in_loop = any(lo <= payload.lineno <= hi for lo, hi in loops)
        rows.append((section, quantity, where, source, in_loop))
    return rows


def render(rows, syms):
    out = []
    A = out.append
    n_sites = len(rows)
    n_loops = sum(1 for r in rows if r[4])
    A("Every quantitative claim in `main.tex` is registered exactly once")
    A("as a `claim(...)` call in `scripts/verify_numerics.py`.  The table below is")
    A("extracted from that file, so it cannot drift from the audit it describes:")
    A("the third column IS the expression the audit evaluates.")
    A("")
    A("- call sites listed below: **%d**" % n_sites)
    A("- of which inside a loop (so one site evaluates several times): **%d**"
      % n_loops)
    A("- entries `verify_numerics.py` reports at run time: see the header of")
    A("  `scripts/verification_report.md`")
    A("")
    A("Symbols appearing in the third column:")
    A("")
    A("| symbol | resolves to |")
    A("|---|---|")
    for k in sorted(syms):
        A("| `%s` | %s |" % (k, syms[k]))
    A("")
    for sec in dict.fromkeys(r[0] for r in rows):
        sub = [r for r in rows if r[0] == sec]
        A("**%s** (%d call sites)" % (sec, len(sub)))
        A("")
        A("| manuscript quantity | where | produced by |")
        A("|---|---|---|")
        for _, q, w, src, in_loop in sub:
            A("| %s | %s | `%s`%s |"
              % (q, w, src, " *(loop)*" if in_loop else ""))
        A("")
    A("Generated by `scripts/provenance_map.py` from "
      "`scripts/verify_numerics.py` -- %d claim call sites." % n_sites)
    return "\n".join(out)


def main() -> int:
    source = io.open(VERIFY, encoding="utf-8").read()
    tree = ast.parse(source)
    rows = collect_claims(tree)
    syms = collect_symbols(tree)

    # Fail loudly if any claim's producing expression could not be read.  This
    # parser takes the FIFTH POSITIONAL argument of each claim(...) call; if a
    # future edit passes ``computed`` as a keyword (or reorders the signature),
    # args[4] silently becomes something else and the table would describe the
    # wrong expression without anyone noticing.  A "?" in the produced-by column
    # is useless to a maintainer, so treat it as a hard error instead.
    unresolved = [r for r in rows if r[3] == "?"]
    if unresolved:
        print("ERROR: %d claim(s) have no resolvable producing expression:"
              % len(unresolved))
        for sec, q, w, _, _ in unresolved:
            print("  [%s] %s  (%s)" % (sec, q, w))
        print("       provenance_map.py reads the fifth POSITIONAL argument of")
        print("       each claim(...)/claim_order(...) call.  Keep `computed`")
        print("       positional, or teach this parser about the new call form.")
        return 1

    body = render(rows, syms)

    readme = io.open(README, encoding="utf-8").read()
    if BEGIN not in readme or END not in readme:
        print("ERROR: the provenance markers are missing from README.md.")
        print("       Expected both of:")
        print("         %s" % BEGIN)
        print("         %s" % END)
        print("       Refusing to guess where the table belongs.")
        return 1
    head, rest = readme.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    with io.open(README, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(head + BEGIN + "\n" + body + "\n" + END + tail)
    print("Updated the provenance block in README.md "
          "(%d claim call sites, %d symbols)" % (len(rows), len(syms)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
